<?php
define('DB_DIVER','mysql');
define('DB_HOST','localhost');
define('DB_USER','yehuiyang');
define('DB_PASS','54874664');
define('DB_NAME','log');
define('DB_PORT',3306);
define('DB_CHAR','utf8');
//防止模板被盗
define('TCP',true);